name: Check deps

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
  pull_request:

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 18

    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm audit
